Add HTML Style guide
balancebrain/pdr-convention pull request #8
Opened 2017-09-08 07:14 UTC by kyhsa93

Google HTML Style Guide의 내용을 추가했습니다

2017-09-11 00:28 UTC, soliven25 commented on html.md
> +0. 항상 HTTPS 프로토콜 (https:)을 사용한다.
항상 https: 를 사용하면 https 가 아닌것은 http로 변경되니 https를 사용하라는 거죠?

2017-09-11 00:29 UTC, soliven25 commented on html.md
> +0. HTML5를 사용하고 빈 tags는 닫지 않는다.
빈 tags는 닫지 않는다는게 어떤 경우 인가요?

2017-09-11 07:46 UTC, Edunga1 requested changes

2017-09-11 07:46 UTC, Edunga1 commented on html.md
> +0. 항상 HTTPS 프로토콜 (https:)을 사용한다.
HTML이니 API 호출은 아닐텐데, 어디서 https를 사용하라는 뜻인가요?
js, css 임포트 시 URL? 리소스 URL?

2017-09-11 07:46 UTC, Edunga1 commented on html.md
> +0. 모든 코드는 소문자로 작성한다.
HTML 속성도 포함되나요? 그러면 angular 프로젝트인 경우 ngFor는 어떻게 하나요?

2017-09-11 07:46 UTC, Edunga1 commented on html.md
> +0. HTML5를 사용하고 빈 tags는 닫지 않는다.
'HTML5를 사용한다'에 대해서 좀 더 자세하게 설명 부탁드립니다.

2017-09-11 07:46 UTC, Edunga1 commented on html.md
> +0. 생략 가능한 tags는 생략한다. (`<html>`, `<head>`, `<body>` 등)
여기에 해당하는 태그 목록을 나열해주면 좋을 거 같습니다.

2017-09-11 07:46 UTC, Edunga1 commented on html.md
> +0. type 속성은 생략한다.
```<input type="text">``` input 태그도 적용 되나요?

2017-09-11 07:46 UTC, Edunga1 commented on html.md
> +0. 모든 child element는 new line을 사용한다.
예시 코드가 있으면 좋을 거 같습니다

2017-09-12 01:36 UTC, SeonghuiChoe commented on html.md
> +0. type 속성은 생략한다.
type속성이 있는 element가 [button, embed, input, link, menu, object, script, source, style] 인듯 한데 이 elements는 type을 다 생략하는건가요~?

2017-09-12 01:41 UTC, SeonghuiChoe commented on html.md
> +0. type 속성은 생략한다.
type속성이 있는 element가 [button, embed, input, link, menu, object, script, source, style] 인듯 한데 이 elements는 type속성을 다 생략하는건가요~?

2017-09-12 01:41 UTC, SeonghuiChoe commented on html.md
> +0. HTML5를 사용하고 빈 tags는 닫지 않는다.
빈 tags는 뭐가 있나요~?

2017-09-12 01:42 UTC, SeonghuiChoe commented on html.md
> +0. HTML5를 사용하고 빈 tags는 닫지 않는다.
빈 tags는 어떤것들이 있나요~?

2017-09-15 01:10 UTC, kyhsa93 commented
내용을 다시 정리해서 amend할 예정입니다.

2017-09-18 02:42 UTC, Edunga1 approved these changes

2017-09-26 01:15 UTC, SeonghuiChoe approved these changes
LGTM:)

2017-09-27 06:24 UTC, seungwoohong approved these changes
LGTM;

2017-09-27 06:36 UTC, angelgun approved these changes
수고하셧습니다

2017-09-27 07:56 UTC, merged